.bowerrc

Without this, `bower install` puts dependencies under `app/components`, which causes a `npm run build` failure. On Fedora 25, npm 4.4.1, bower 1.8.0.
cc @spadgett @jwforres @jeff-phillips-18

Fixes bower_components directory resolve issue

---

app/mockServices/mockData.service.ts
app/pages/home/homePageController.ts

Final tweeks to truly be able to switch between mock and real retrieval of serviceclasses from Service Catalog API.

Fixes for retriving real and mock serviceclasses

---

config/webpack.dev.js

Use `inline-source-map` for development

---

package.json

Avoids the following error:
All declarations of 'WeakMap' must have identical type parameters.

Lock @types/lodash to 4.14.51

---

app/mockServices/mockData/services.ts
app/mockServices/mockKeywords.service.ts
app/pages/home/home-page.html
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/catalog-search/catalog-search-result.html
src/components/catalog-search/catalog-search.component.ts
src/components/catalog-search/catalog-search.controller.ts
src/components/catalog-search/catalog-search.html
src/components/landing-page/landing-page.component.ts
src/components/landing-page/landing-page.controller.ts
src/components/landing-page/landing-page.html
src/index.ts
src/styles/landing-page.less
test/landing-page.spec.ts

Basic search support, with little styling.
TODO:

Add search to catalog

---

dist/origin-web-catalogs.css
src/styles/landing-page.less
src/styles/variables.less

Visual updates to landing page search bar. Does not include css to make the search bar sticky.

Add visual styles to search

---

bower.json
package.json

Changed semantic versioning to retrieve all origin-web-common 0.0 minor versions
This picks up origin-web-common@0.0.11 which contains the ui-select styles for the `<select-project>` component.

Fixes #87 - The <select-project> component shows offset highlight when selecting a project

---

dist/origin-web-catalogs.js
src/components/services-view/services-view.controller.ts

Sort subcategory items. Currently, sometimes the builders appear first and sometimes the service classes appear first. They should be sorted as one list by display name.

Sort catalog items

---

dist/origin-web-catalogs.css
src/styles/landing-page.less

There is extra padding at mobile sizes to account for a fixed search bar, but the search bar is no longer fixed at mobile.
Fixes #110

Remove unnecessary top padding from header

---

dist/origin-web-catalogs.css
src/styles/landing-page.less

The typeahead dropdown was using some styles that aren't needed and
caused some minor visual problems when integrated in the console.
Fixes this issue:

Remove unnecessary styles from search results

---

dist/origin-web-catalogs.js
src/components/order-service/order-service-review.html
src/components/order-service/order-service.controller.ts

The message would show "Create Project" as the project display name when provisioning services into a new project.

Fix message when service provisioned into new project

---

dist/origin-web-catalogs.js
src/filters/projectUrl.ts

Default to relative URL `project/` instead of `/` for the default base URL. This will work correctly when running in the web console.

Default to `project/` for base project URL

---

dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder.controller.ts

The prevents incorrectly accepting names with spaces or other names where only a substring matches the pattern.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1443046

Bug 1443046 - The application name pattern should match the entire value

---

app/pages/home/home-page.html
app/pages/home/homePageController.ts
dist/origin-web-catalogs.js
src/components/catalog-search/catalog-search.component.ts
src/components/catalog-search/catalog-search.controller.ts
src/components/projects-summary/projects-summary.component.ts
src/components/projects-summary/projects-summary.controller.ts
src/components/services-view/services-view.component.ts
src/components/services-view/services-view.controller.ts
src/components/services-view/services-view.html
src/services/catalog.service.ts
test/projects-summary.spec.ts
test/services-view.spec.ts

In `<catalog-search>`, `<services-view>`, and `<projects-summary>` replaced attributes `service-classes` and `image-streams` with a single attribute `catalog-service-items`.  `catalog-items` are retrieved via `CatalogServices` class.  
This PR basically removes a bunch of data normalization functions, which were duplicated in the three components listed above, and centralizes them in CatalogServices.

Consolidated retrieval of Catalog Service Items

---

dist/origin-web-catalogs.js
src/constants.ts
test/saas-list.spec.ts

Some dependency update causes the build to fail do to exporting from an non-module based file. The exports were included only to allow easy access from the test specs.
Removed the exports and updated the test spec to use the constants appropriately.

Remove unnecessary exports from Constants

---

app/pages/home/homePageController.ts
dist/origin-web-catalogs.js
src/services/catalog.service.ts

Show toast notification when one of the catalog types can't be loaded:
Fixes #194 
When console uses this version, must update [landingPage.js](https://github.com/openshift/origin-web-console/blob/master/app/scripts/controllers/landingPage.js#L54) to be similar to [homePageController.js](https://github.com/openshift/origin-web-catalog/pull/213/files#diff-a5664f9aa9719119bc4a5ebe9f95c541R43)

Don't completely fail when one of the catalog types can't be loaded

---

dist/origin-web-catalogs.js
src/components/order-service/order-service.controller.ts
src/components/select-project/select-project.controller.ts
src/services/catalog.service.ts
test/select-project.spec.ts

Hi,
This fixes https://bugzilla.redhat.com/show_bug.cgi?id=1449268
Also tested that the 'create-project' form fields are persisted between wizard steps as well.

Remember selected-project when going between steps of Ordering Panel

---

dist/less/overlay-panel.less
dist/origin-web-catalogs.css
src/styles/overlay-panel.less

Fixing bug where wizard steps indicator was too narrow in IE11

---

dist/less/catalog.less
dist/less/mixins.less
dist/less/order-service.less
dist/less/overlay-panel.less
dist/origin-web-catalogs.css
src/styles/catalog.less
src/styles/mixins.less
src/styles/order-service.less
src/styles/overlay-panel.less

Fixes #196 
At a tall, wide desktop resolution, very long descriptions clip if they exceed the max-height of the panel
At short, wide desktop resolution, very long descriptions clip and the right side panel scrolls if the contents are taller than the panel
At mobile, there is no change in the behavior and the two columns collapse to one and there is an inner scroll
Whatchyall think?  @jwforres, @spadgett, @sg00dwin, @serenamarie125, @beanh66, etc.

Making only right side panel contents scrollable, left side panel content clip

---

dist/origin-web-catalogs.js
src/components/services-view/services-view.controller.ts
src/components/services-view/services-view.html
src/services/catalog.service.ts
test/services-view.spec.ts

Previously, each catalog item kept track of it's own associated categories & sub-categories.  This PR removes categories/sub-categories from catalog items and instead  categorizes each item into an items array under each sub-category in the main Catalog object (similar to console's `buildersByCategory` object).   Categorization also dynamically adds 'All' and 'Other' main and sub-categories when needed.
This allows quicker processing as we only have to cycle through the category items once to categorize them whereas previously each catalog item ran through each category/sub-category, and then a second pass to remove those categories/sub-categories which weren't associated with any items.
This also allows for cleaner filtering code in the `<service-view>` component.
All unit tests passed …

Optimize Catalog Item Retrieval

---

dist/origin-web-catalogs.js
src/components/order-service/order-service.controller.ts

Prevent some button flicker when the provision service overlay is first displayed by setting it to `updating` initially.

Avoid button flicker in provision service dialog

---

app/mockServices/mockAlertMessage.service.ts
app/pages/home/homePageController.ts
dist/origin-web-catalogs.js
src/components/projects-summary/projects-summary.controller.ts

These methods are not longer used by the web console in favor of toast notifications and will be removed. See https://github.com/openshift/origin-web-console/pull/1679

Remove AlertMessageService.addAlert() / getAlerts() / clearAlerts()

---

dist/origin-web-catalogs.js
src/components/order-service/order-service-configure.html
src/components/order-service/order-service.controller.ts

If present in the parameter schema, hide the requester-username parameter in the form and send the current username as the parameter value when provisioning a service. This parameter is required by the template broker.
Fixes #291
cc @jim-minter @bparees

Send the `template.openshift.io/requester-username` parameter

---

dist/less/services-view.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/services-view/services-view.controller.ts
src/components/services-view/services-view.html
src/constants.ts
src/styles/services-view.less

This PR scrolls the ‘Browse Catalog’ section to the top of the landing page when a category is selected. This makes it so the page doesn't 'jump' while browsing through the available categories.
Fixes #267 
Jumping issue:
Before:
After"

Scroll service categories to top on selection

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

Bug as seen in console:
Console using this fix:

Fixes bug in console where category/subcategory arrows are misaligned

---

app/mockServices/mockData/services.ts
dist/origin-web-catalogs.js
src/components/order-service/order-service.controller.ts

Fixes #294 
Bug only affected provisioning a service class.  Provisioning builder images uses slightly different logic and isn't effected by this bug.

Fixes 'Next never enables if provision service and no projects exist'

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

The bottom "border" on the last category/subcategory nav item grabs my eye in a bad way.  Eliminating it resolves the issue.
Before:
After:

Removing bottom border from last category/subcategory nav item at mobile

---

app/mockServices/mockData/services.ts

`bindable` is a required parameter on service class.

Add bindable to mock service class data

---

app/app.less
bower.json

Messenger was removed from common in favor of Patternfly toasts.

Remove messenger dependency from sample app

---

dist/origin-web-catalogs.js
src/constants.ts

By default, do not auto-launch landing page tour on first access

---

dist/origin-web-catalogs.js
src/components/services-view/services-view.controller.ts

I'm assuming this placeholder text should use headline case since "Category" is capitalized. Also "Search Catalog" is headline. It looks odd to me with lowercase "keyword" and uppercase "Category."

Use headline case consistently for placeholder text

---

dist/origin-web-catalogs.js
src/components/services-view/services-view.controller.ts

Fixes #341 
One line change to filter out any 'filters' which do not have keyword 'values' (empty filters)
Filed a-pf Issue: patternfly/angular-patternfly#509

Prevent applying empty keyword filter

---

dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder.controller.ts

- Don't block the user from creating from builder if there's an error getting the instances
- Fix an error where the watch isn't closed when switching projects, which means the instances listed in the dialog might be for the wrong project
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1471040

Bug 1471040 - Don't block builder flow if can't get instances

---

dist/origin-web-catalogs.js
src/components/order-service/order-service-configure.html
src/services/catalog.service.ts

Fix a problem where a runtime error occurs when the `displayName` for a service class is explicitly set to `null` (rather than undefined).
@dymurray

Avoid runtime error when service class displayName set to null

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

Resulting in improper sizing of .service-item
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1473615
Note:  Release of origin-web-catalog and consumption of said release by origin-web-console required to fully resolve bug.
After:

Fixes IE11 bug where .service-items didn't properly size

---

bower.json
package.json

Bumping versions so we can update Patternfly in origin-web-console without bower overrides. Needed to pick up @jeff-phillips-18's fix for the dialog next button callback.

Bump version to 0.0.34

---

app/mockServices/mockProjects.service.ts
app/mockServices/mockRecentlyViewedProjects.service.ts
app/mockServices/mockServices.module.ts
dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder.controller.ts
src/components/order-service/order-service.controller.ts
src/components/projects-summary/projects-summary.controller.ts

DO NOT MERGE until origin-web-common's version is bumped!
This is the second PR towards resolving issue [console:#1895](https://github.com/openshift/origin-web-console/issues/1895)
ProjectSummary updated to use RecentlyViewedProjects.orderByMostRecentlyViewed(..).  CreateFromBuilder and OrderService wizards updated to use ProjectServices.create(...).

In Project Summary sidebar, order by most recently viewed projects

---

dist/origin-web-catalogs.js
src/components/select-project/select-project.controller.ts

We filter projects marked for deletion in the select-project component,
but we should use the unfiltered list for detecting if the name is unique.
@rhamilto FYI

Use the unfiltered project list for determining if name is unique

---

dist/origin-web-catalogs.js
src/components/select-project/select-project.component.ts
src/components/select-project/select-project.controller.ts
src/components/select-project/selectProject.html
test/select-project.spec.ts

The following changes have been made to the ```<select-project>``` component:
- Accepts a list of projects, so another projects retrieval is not needed (performant)
- Callback method when project selected.
- Does not select a project by default, unless there is only one project
- required asterisk, error msg if user clicks on dropdown, but doesn't select a project 
- Sorts projects by displayName
**No Project Selected**
**User clicks on then off dropdown, and doesn't select a project:**
**Project Selected**
Fixes:  https://github.com/openshift/origin-web-console/issues/1833

Don't select a default project if there is more than one project

---

app/mockServices/mockData/services.ts
dist/less/order-service.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/catalog-parameters/catalog-parameters.component.ts
src/components/catalog-parameters/catalog-parameters.controller.ts
src/components/order-service/order-service-configure.html
src/components/order-service/order-service.controller.ts
src/styles/order-service.less
test/services-view.spec.ts

Allows the OpenShift UI to enforce order, grouping, and display type, if that information is supplied by the broker.  Brokers are responsible for adding the form definition in the plan metadata as `schemas.service_instance.create.form_definition`  (A similar path for service_binding.create can also be supplied this way, but out of scope fort his PR).   
Unfortunately, regarding grouping, fieldset and section html is generated properly, but has no visual difference.  This would take additional work to style appropriately. (picture below)
Example broker code:
https://github.com/openshift/ansible-service-broker/pull/386 
Example json gist:
https://gist.github.com/cfchase/8614236dcb8e22cc0aa8a2b4f1ee52d0
Screenshots
Full Wizard:
Example display types of fields:
Fieldset not styled:

Read and use form definition for parameters if supplied by broker.

---

.gitignore
bower.json
package.json

- use `>` for angular-patternfly 
- add DS_Store to `.gitignore`
We are using `~` right now, which allows for a range in the patch.  I think we should use `>`. 
Perhaps `>=` would be better:
`"angular-patternfly": ">=4.3.0"`
as we should be able to expect future minor changes to work as well. We can add a limit if it makes sense:
`"angular-patternfly": ">=4.3.0 <5.0.0"`
This should clarify that `openshift-web-console` is the source of truth & simplify bumping the dependencies.  It does assume `semver` is followed closely & breaking changes will not be introduced without a major version bump.
@spadgett @jeff-phillips-18 ?
Relevant for [this PR](https://github.com/openshift/origin-web-console/pull/1988)

Update angular-patternfly dependency to "at least" syntax

---

app/mockServices/mockBinding.service.ts
dist/origin-web-catalogs.js
src/components/order-service/order-service-bind-parameters.html
src/components/order-service/order-service.controller.ts
src/components/order-service/order-service.html
src/index.ts

https://trello.com/c/Sws4p5jU
Requires https://github.com/openshift/origin-web-common/pull/163
See also https://github.com/openshift/origin-web-console/pull/1987
@jeff-phillips-18 FYI

Support bind parameters

---

dist/origin-web-catalogs.js
src/components/catalog-parameters/catalog-parameters.controller.ts

When changing plans, the form definition wasn't being updated.  As a result, only the first plan's form definition was shown.  This change updates the displayed form definition whenever the input form definition is changed (such as by changing plans)

Update catalog-parameters form definition when changed.

---

dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder.controller.ts
src/components/create-from-builder/create-from-builder.html
src/components/order-service/order-service.controller.ts
src/components/order-service/order-service.html

* Prevent users from accidentally creating something by clicking one of the numbered steps.
* Fix a bug in the builder dialog where the button label incorrectly said "Next >" instead of "Create" when pod presets are disabled
See https://github.com/openshift/origin-web-console/issues/1829

Prevent navigating to review step by clicking number

---

app/mockServices/mockData/services.ts
dist/origin-web-catalogs.js
src/components/catalog-search/catalog-search-result.html
src/components/order-service/order-service.controller.ts
src/services/catalog.service.ts
test/services-view.spec.ts

https://trello.com/c/y1lbFrbp
Since service-catalog 0.0.18, the alpha prefix has been removed from all fields in favor of feature gating. Make the corresponding API changes in the web catalog.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1492991

Bug 1492991 - Remove alpha prefix from service catalog properties

---

app/config.js
config/webpack.dev.js

https://github.com/webpack/webpack-dev-server/issues/1090 includes details of the webpack-dev-server issue.  
**Important: in order to make use of this fix, add:**
```
window.DEV_TOOL_SETTING = 'inline-source-map';
```
to your `app/config.local.js` file when you need to test in Safari.  Note this will significantly slow down build and rebuild, so use it only when testing in Safari.
Thanks, @jeff-phillips-18, for the assist on this one.

Workaround for webpack-dev-server issue with Safari

---

app/mockServices/mockData/services.ts
bower.json
dist/less/order-service.less
dist/less/overlay-panel.less
dist/less/variables.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
package.json
src/components/create-from-builder/create-from-builder-bind.html
src/components/create-from-builder/create-from-builder-configure.html
src/components/create-from-builder/create-from-builder-info.html
src/components/create-from-builder/create-from-builder-results.html
src/components/create-from-builder/create-from-builder.controller.ts
src/components/create-from-builder/create-from-builder.html
src/components/landing-page/landing-page.html
src/components/order-service/order-service-bind-parameters.html
src/components/order-service/order-service-bind.html
src/components/order-service/order-service-configure.html
src/components/order-service/order-service-info.html
src/components/order-service/order-service-plans.html
src/components/order-service/order-service-review.html
src/components/order-service/order-service.controller.ts
src/components/order-service/order-service.html
src/components/overlay-panel/overlay-panel.component.ts
src/components/overlay-panel/overlay-panel.html
src/index.ts
src/styles/order-service.less
src/styles/overlay-panel.less
src/styles/variables.less

Changing overlay layout to a single column

---

dist/origin-web-catalogs.js
src/components/order-service/order-service.controller.ts

Requires https://github.com/openshift/origin/pull/16434
The template broker no longer needs the special `template.openshift.io/requester-username` parameter now that service-catalog 0.0.20 sends the originating identity header. Remove special handling for `requester-username`.

Remove special handling of requester-username parameter

---

dist/origin-web-catalogs.js
src/components/select-project/select-project.controller.ts

Issue was that the 'canIAddToProject' rule was expected to be loaded via the project 'rules' via a 'get'.  Fixed so that project rules are loaded if they are not in the AuthorizationService project rules cache.
Screenshots of launching the Ordering Panel without ever going to a View Project screen:
Fixes #318

In ordering panel, if user selects project which they have 'view only' access, show error

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

Fixes https://github.com/openshift/origin-web-catalog/issues/462

IE11 needs a defined width on the flex container to prevent overflow

---

dist/less/order-service.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder-info.html
src/components/services-view/services-view.html
src/constants.ts
src/services/catalog.service.ts
src/styles/order-service.less

Use SVG icons when available.
See https://github.com/openshift/origin-web-console/pull/2208
Requires https://github.com/openshift/origin-web-common/pull/213

Add SVG icons

---

dist/origin-web-catalogs.js
src/services/catalog.service.ts

The service class description is missing from our dialogs after the API changes. I missed this because long-description was showing up.
@rhamilto FYI

Fix missing service class description

---

app/mockServices/mockData/services.ts
dist/origin-web-catalogs.js
src/services/catalog.service.ts

Hide items with a 'hidden' tag

---

app/mockServices/mockAPI.service.ts
app/mockServices/mockData.service.ts
app/mockServices/mockData/plans.ts
app/mockServices/mockData/services.ts
bower.json
dist/origin-web-catalogs.js
package-lock.json
package.json
src/components/landing-page/landing-page.controller.ts
src/components/landing-page/landing-page.html
src/components/order-service/order-service.controller.ts
src/services/catalog.service.ts
test/services-view.spec.ts

Requires https://github.com/openshift/origin-web-common/pull/223
Updates origin-web-common to 0.0.66
* Cluster prefix for service classes and plans
* ServiceInstanceCredential -> ServiceBinding
* check removedFromBrokerCatalog
TODO:
cc @jeff-phillips-18

Adopt more service catalog API changes

---

dist/less/overlay-panel.less
dist/origin-web-catalogs.css
src/styles/overlay-panel.less

Simple fix for https://github.com/openshift/origin-web-console/issues/2095

Fix to scroll when overlay panel is too tall for viewport

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

In the cases where SVG images were wider than they were tall, setting a height didn't work.  Changing to width does work since all of our SVGs are wider than they are tall or are square.  If we end up with SVGs that are taller than they are wide, we may end up with this bug again.
Supports https://github.com/openshift/origin-web-console/issues/2278

Fixing bug where SVG images were clipping in IE11

---

dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder.controller.ts

Don't load service classes and plans in the builder dialog if there are no pod presets.
Fixes #511

Don't load service classes and plans if no pod presets

---

app/mockServices/mockData/openshift-images.ts
dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder-info.html
src/components/create-from-builder/create-from-builder.controller.ts
src/components/order-service/order-service-info.html
src/services/catalog.service.ts
test/services-view.spec.ts

Waiting for consensus on the name in https://github.com/openshift/origin/issues/16755
@sspeiche

Look for provider display name annotation on image streams

---

dist/less/projects-summary.less
dist/origin-web-catalogs.css
src/styles/projects-summary.less

Fixes https://github.com/openshift/origin-web-catalog/issues/506

Make recently view item logos have max-height and max-width of 32px

---

dist/less/catalogParameters.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
package-lock.json
src/components/update-service/update-service.controller.ts
src/styles/catalogParameters.less

Also fixes next button title going back to the plan page of the update service wizard.

Fix readonly parameters margins

---

dist/origin-web-catalogs.js
src/components/update-service/update-service.controller.ts

The logic was reversed deciding to hide the plans step when updating a service instance.
See https://github.com/openshift/origin-web-console/issues/2350

Fix planUpdatable check

---

dist/origin-web-catalogs.js
src/components/order-service/order-service.controller.ts

Avoid `ng-repeat` errors by filtering duplicates from the dependencies array.
Fixes #528

Avoid errors when an image dependency appears twice

---

dist/origin-web-catalogs.js
src/components/services-view/services-view.controller.ts

We were accidentally registering the resize listener twice and only
removing one, leaking listeners every time the page was visited. Only
register the listener once.

Don't leak resize listeners in catalog services view

---

app/mockServices/mockData/services.ts
dist/origin-web-catalogs.js
src/services/catalog.service.ts
test/services-view.spec.ts

For service classes, use the external name when there's no display name set.
This prevents the internal UID from being shown in the UI.
https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/v1beta1/types.go#L244-L246
Fixes:
@ncameronbritt @jwforres

Fall back to external name when no display name is set

---

dist/less/overlay-panel.less
dist/less/variables.less
dist/origin-web-catalogs.css
src/styles/overlay-panel.less
src/styles/variables.less

Supports https://github.com/openshift/origin-web-console/issues/2442
Since [VH units are essentially unusable on mobile devices](https://stackoverflow.com/a/37113430), this PR changes the modal to use fixed positioning at mobile screen sizes (viewport width < 767px) so that the modal is always the full-size of the viewport (thus eliminating the flicker) without the mobile browser chrome overlaying the footer.
Additionally, I improved upon the layout for desktop resolutions so that shorter viewport heights maximize the available space.

Make modals fullscreen at < 768px width

---

dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder.controller.ts

Don't try to request service classes or plans in the create from builder
dialogs when pod presets are disabled.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1512858
/kind bug

Bug 1512858 - Don't request service classes and plans for builders

---

app/mockServices/mockData.service.ts
dist/origin-web-catalogs.js
src/components/projects-summary/projects-summary.controller.ts

Correctly check the projects size before attempting to watch projects.
Also fixes the mock data service to correctly return a large project list on the first call to `list()`.

Fix project size check for projects sidebar

---

dist/origin-web-catalogs.js
src/components/catalog-filter/catalog-filter.component.ts
src/components/catalog-filter/catalog-filter.controller.ts
src/components/services-view/services-view.controller.ts
src/components/services-view/services-view.html
src/services/catalog.service.ts

Remove the determination of categories and vendors from the calls to get catalog items (either project or all). Rather, add methods to determine and return these based on a list of catalog items.
Fixes #586

Do not store categories or vendors in Catalog service

---

dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder.controller.ts

In the create from builder dialog, handle image streams that are from namespaces other than `openshift`.
https://github.com/openshift/origin-web-console/pull/2563 lets you use builders from another namespace.
/kind bug
/assign @jwforres 
/cc @jwforres @jeff-phillips-18

Don't assume image stream is from openshift namespace

---

dist/origin-web-catalogs.js
src/services/catalog.service.ts

This one is likely the last.  I'll fish around a bit for some oddities, like hard-coded `{resource: '', group: ''}`, but we should be in good shape at this point.

Update catalog service to use getPreferredVersion

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

- removes ng-leave transition to prevent 'services-no-sub-categories' from briefly showing when markup is present.

Fine tuning of positioning and alignment during transitions.

---

dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder.controller.ts

Don't assume changing locations will cause the panel to close.
See https://github.com/openshift/origin-web-console/issues/2624
/kind bug

Close panel when navigating to advanced options

---

app/app.less
app/styles/variables.less
dist/less/landing-page.less
dist/less/variables.less
dist/origin-web-catalogs.css
src/styles/landing-page.less
src/styles/variables.less

Supports https://github.com/openshift/origin-web-console/issues/2701
And additional search-related cleanup:
* remove redundant and incorrect landing positioning rules
* fix bug where project picker was masked by search input at mobile [1]
[1] 
Before:
After:

Fix bug where landing search obscures primary nav at mobile

---

dist/less/animations.less
dist/less/services-view.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/catalog-filter/catalog-filter.controller.ts
src/styles/animations.less
src/styles/services-view.less

Prevent duplicate catalog keyword filters from being applied.   Case insensitive.   Upon entering a duplicate keyword, the existing keyword filter tag/chip "flashes":
Related Issue: https://github.com/openshift/origin-web-catalog/issues/617

Catalog Filter: prevent duplicate keyword filters

---

dist/origin-web-catalogs.js
src/components/catalog-filter/catalog-filter.controller.ts

So, previous iteration of this worked in the Catalog demo app., but not in Console  -I did the newbie mistake of not 'bower linking' my catalog dev code to console and making sure it actually ran in Console.  
This update makes the `querySelectorAll` more specific, while at the same time making the `_find the dup keyword filter tag/result_' matching logic more generic.

Catalog Filter Panel: better logic to find duplicate filter result tag to flash

---

dist/origin-web-catalogs.js
src/components/select-project/select-project.component.ts
src/components/select-project/select-project.controller.ts

For Bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1540490
The `<select-project>` component lists all projects a user can view and when user selects a project, does `canIAdd` validation, typically because `<select-project>` is used in all the 'AddToProject' dlgs/wizards (deployImage, fromFile, process-template, etc..).   
When `<select-project>` is used in the Set Home Pref dlg., we do not care if user canAdd to the project, so added a param to skip this validation check.

Select Project component: added ability to skip canIadd validation check

---

dist/less/overlay-panel.less
dist/origin-web-catalogs.css
src/styles/overlay-panel.less

Supports https://github.com/openshift/origin-web-console/issues/2761
Note:  .landing and .landing-side-bar benefit from this same fix;
however, the application of the fix causes .landing-side-bar to
disappear as -webkit-overflow-scrolling: touch changes the behavior of
position: fixed.  I will work to see if I can find a workaround and
open a separate PR.

Resolve bug where overlay wizard scrolling is sluggish

---

dist/less/mixins.less
dist/less/overlay-panel.less
dist/origin-web-catalogs.css
src/styles/mixins.less
src/styles/overlay-panel.less

The override fix is no longer required for Safari 11, and the override was
breaking the shadow behavior in mobile Safari now that
-webkit-overflow-scrolling: touch is enabled.

Remove scroll shadow overrides for Safari

---

dist/origin-web-catalogs.js
src/services/catalog.service.ts

Helps remove one possible cause of https://github.com/openshift/origin/issues/18569 since we won't need to check for the template service broker on pod startup.
/assign @dtaylor113 
@deads2k @jwforres cc

Check service classes to determine if template service broker is enabled

---

dist/origin-web-catalogs.js
src/filters/projectUrl.ts

This avoids flicker when you're already on the overview and you click "Continue to project overview" in a wizard dialog.
/assign @rhamilto

Use `/overview` in projectUrlFilter

---

dist/origin-web-catalogs.js
package-lock.json
package.json
src/constants.ts

Adding 3scale to the middleware list.
I'm assuming here that the `tags` array will match with the OS template tags.
cc @spadgett

introducing 3scale in the middleware integration list

---

dist/origin-web-catalogs.js
src/constants.ts

Add MS SQL subcategory to databases. Will allow the following APB to be displayed under databases in catalog:
https://github.com/ansibleplaybookbundle/mssql-apb
Depends on https://github.com/openshift/origin-web-console/pull/2941 for its image.

add mssql to databases category
