app/app.ts
app/config.js
app/pages/error/error-page.html
app/pages/error/errorPage.ts
app/pages/error/errorPageController.ts
app/pages/home/homePageController.ts
app/pages/services/servicesPageController.ts
app/routes.ts
bower.json

Also:
- Added try/catch to gracefully handle when cannot retrieve serviceclasses from Service Catalog API
- Updated config.js to include the additionalServers block.
- Fixes #14

Added Error Page and Routing

---

package.json

Match Lodash v3, which is what's in bower.json.
Fixes #37

Use @types/lodash ^3.10.1

---

config/webpack.prod.js
dist/origin-web-catalogs.js
dist/vendor-bundle.js

Preserve newlines in minified JS to help with merge conflicts

---

app/app.ts
app/mockServices/mockData.service.ts
app/pages/home/home-page.html
bower.json
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
package.json
src/components/projects-summary/projects-summary.component.ts
src/components/projects-summary/projects-summary.controller.ts
src/components/projects-summary/projects-summary.html
src/constants.ts
src/filters/projectUrl.ts
src/index.ts
src/styles/projects-summary.less
test/projects-summary.spec.ts
test/utils/testHelpers.ts

Show Getting Started when less than 2 projects exist
Add project name and creator to project list items
Add 'View and Edit Membership" menu item to projects
Add Start Guided Tour button
Add resource links (actual links and text are TBD)
Fixes #39

Updates to project summary panel

---

app/app.less
app/app.ts
app/mockServices/mockData.service.ts
app/mockServices/mockData/projects.ts
app/mockServices/mockData/services.ts
bower.json
config/webpack.dev.js
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
package.json
src/components/order-service/order-service-configure.html
src/components/order-service/order-service.controller.ts
src/components/order-service/order-service.html
src/components/projects-summary/projects-summary.controller.ts
src/components/select-project/select-project.component.ts
src/components/select-project/select-project.controller.ts
src/components/select-project/selectProject.html
src/index.ts
src/styles/order-service.less
test/projects-summary.spec.ts
test/select-project.spec.ts
test/utils/testHelpers.ts

Created a `<select-project>` component which allows one to select or create a new project.  Integrated into the serviceClass order service:
The most recently created project is selected by default.
**Project keyword search:**
**Create Project with validation:**
Duplicate project name validation also implemented.

select-project component

---

dist/origin-web-catalogs.js
src/components/select-project/selectProject.html

Fixes the following issue where the inputs are cut off.

Fix the create project form inputs on mobile

---

dist/origin-web-catalogs.css
src/styles/landing-page.less

Making fixed positioning of search only occur at non-mobile

---

dist/origin-web-catalogs.js
src/services/catalog.service.ts

Correctly show service class description

---

dist/origin-web-catalogs.js
src/components/catalog-search/catalog-search.controller.ts

Correctly search service class tags

---

dist/origin-web-catalogs.css
src/styles/landing-page.less

Fixes https://github.com/openshift/origin-web-console/issues/1412

Prevent navbar menus opening below sidebar

---

dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/projects-summary/projects-summary.controller.ts
src/styles/landing-page.less
src/styles/projects-summary.less

Dis-allow outside actions when showing Create/Edit project panel

---

dist/origin-web-catalogs.css
src/styles/landing-page.less
src/styles/services-view.less

An alternate coloration of the subcategory background

Change subcategory background color

---

app/index.html
app/mockServices/mockData.service.ts

Add toast notifications to the showcase application

---

dist/less/projects-summary.less
dist/less/services-view.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/projects-summary/projects-summary.html
src/components/services-view/services-view.html
src/styles/projects-summary.less
src/styles/services-view.less

Removing inner scroll from service subcategories

---

dist/origin-web-catalogs.js
src/services/catalog.service.ts

Setup for locale case insensitive comparison/sort, reference PR #190, fixes issue #174

Locale Comparison for Catalog Service

---

app/mockServices/mockData/services.ts
app/pages/home/homePageController.ts
dist/origin-web-catalogs.js
src/components/catalog-search/catalog-search.controller.ts
src/components/landing-page/landing-page.component.ts
src/components/landing-page/landing-page.controller.ts
src/components/landing-page/landing-page.html
src/components/order-service/order-service.html
src/services/catalog.service.ts

https://trello.com/c/2A7x5Pbc
Optionally adds templates to the service catalog when the template broker is not running. The template dialog itself is handled in the web console by https://github.com/openshift/origin-web-console/pull/1492

Optionally show templates in the service catalog

---

app/app.less
app/app.ts
app/components/navigation/navigation.controller.ts
app/components/navigation/navigation.html
app/mockServices/mockAuth.service.ts
app/mockServices/mockAuthCfg.constant.ts
app/mockServices/mockServices.module.ts
app/pages/home/home-page.html
app/pages/home/homePageController.ts
app/pages/logout/logout-page.html
app/pages/logout/logoutPage.ts
app/pages/logout/logoutPageController.ts
app/routes.ts
config/webpack.common.js
dist/origin-web-catalogs.js
package.json
src/components/projects-summary/projects-summary.component.ts
src/components/projects-summary/projects-summary.controller.ts
src/components/projects-summary/projects-summary.html
src/constants.ts
test/projects-summary.spec.ts

Please take a look at constants.ts in particular. This is the quick and dirty way of setting up the tour. It is prone to breaking if any of the selectors change. We could define constants for these selectors that could then be more easily updated, but how many to define would be the question. This along with defining functions used to show certain portions of the page (showAllCatalogs, showCategories) should be discussed and I'm open to suggestions.

Add Landing Page Guided Tour

---

app/app.less
bower.json
dist/less/catalog.less
dist/less/main.less
dist/less/variables.less
dist/origin-web-catalogs.css
package.json
src/styles/catalog.less
src/styles/main.less
src/styles/variables.less

Once merged, I'll need a new release cut so I can make use of these changes in console.

Utilizing origin-web-common variables and mixins

---

bower.json
package.json

Bump to v0.0.14

---

dist/origin-web-catalogs.js
src/components/services-view/services-view.html
src/constants.ts
src/services/catalog.service.ts
test/services-view.spec.ts

Please refer to: https://trello.com/c/xbWZVIrz for detailed information about how the categorization algorithm has changed.
Fixes #192 and Fixes #29

New Categorization of Catalog Items

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

Fixes https://github.com/openshift/origin-web-catalog/issues/218
@rhamilto PTAL

switch will-change to border from box-shadow

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

Resolving bug where loading panel has gray background instead of white

---

app/mockServices/mockBinding.service.ts
app/mockServices/mockData.service.ts
app/mockServices/mockData/deploymentConfig.ts
app/mockServices/mockData/deployments.ts
app/mockServices/mockData/replicaSets.ts
app/mockServices/mockData/replicationControllers.ts
app/mockServices/mockData/statefulSets.ts
app/mockServices/mockServices.module.ts
app/pages/home/home-page.html
dist/less/order-service.less
dist/less/overlay-panel.less
dist/less/variables.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder-bind.html
src/components/create-from-builder/create-from-builder-results.html
src/components/create-from-builder/create-from-builder.controller.ts
src/components/create-from-builder/create-from-builder.html
src/components/landing-page/landing-page.component.ts
src/components/order-service/order-service-bind.html
src/components/order-service/order-service-review.html
src/components/order-service/order-service.controller.ts
src/components/order-service/order-service.html
src/components/select-project/select-project.controller.ts
src/filters/applications.ts
src/index.ts
src/styles/order-service.less
src/styles/overlay-panel.less
src/styles/variables.less

Bumps origin-web-common version to v0.0.24
Fixes #232

Add binding capabilities to the order flow. Use Angular PF wizard.

---

app/mockServices/mockAPI.service.ts
dist/origin-web-catalogs.js
src/services/catalog.service.ts

This lets us show the new landing page without the service catalog running.

Only request service classes if available

---

dist/less/mixins.less
dist/less/order-service.less
dist/less/overlay-panel.less
src/styles/mixins.less
src/styles/order-service.less
src/styles/overlay-panel.less

Thanks for noticing the misnomer, @jeff-phillips-18

Correcting misnamed mixin

---

app/mockServices/mockData.service.ts
app/mockServices/mockData/instances.ts

Add mock instance data

---

bower.json
package.json

Bump origin-web-common to 0.0.29 and update catalog to 0.0.18.
Closes #256

Version 0.0.18

---

dist/origin-web-catalogs.js
src/constants.ts
src/services/catalog.service.ts

Fixes https://github.com/openshift/origin-web-catalog/issues/259

Add golang and .Net to the ootb language subcategories

---

dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder.controller.ts
src/components/order-service/order-service.controller.ts

Partial fix for https://github.com/openshift/origin-web-console/issues/1588

Handle project name being changed by project template when ordering

---

dist/less/projects-summary.less
dist/origin-web-catalogs.css
src/styles/projects-summary.less

Preserve newlines and break long strings in project description

---

app/app.ts
app/mockServices/mockData/services.ts
bower.json
dist/origin-web-catalogs.js
package.json
src/components/catalog-parameters/catalog-parameters.component.ts
src/components/catalog-parameters/catalog-parameters.controller.ts
src/components/catalog-parameters/catalog-parameters.html
src/components/order-service/order-service-configure.html
src/components/order-service/order-service.controller.ts
src/constants.ts
src/decorators/bootstrap/array.html
src/decorators/bootstrap/checkbox.html
src/decorators/bootstrap/checkboxes.html
src/decorators/bootstrap/default.html
src/decorators/bootstrap/select.html
src/index.ts
test/utils/testHelpers.ts

https://trello.com/c/qvua05Kh
Initial support for service instance parameters using angular-schema-form.
@jwforres FYI

Support service instance parameters

---

dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder-bind.html
src/components/create-from-builder/create-from-builder-results.html
src/components/create-from-builder/create-from-builder.controller.ts
src/components/order-service/order-service-bind.html
src/components/order-service/order-service-review.html
src/components/order-service/order-service.controller.ts

Fixes #251 
Fixes #257
Fixes #217 
Also fixes displaying errors when creating a project which already exists
Removes filters that were added to common.

Check services/plans for bindability before allowing binding 

---

dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder.controller.ts

Do not pre-select a service to bind when ordering applications

---

dist/less/services-view.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/services-view/services-view.html
src/styles/services-view.less

Improving display of service items filtering widget

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

Bug fix where filter was too big at 320px - 334px viewports

---

app/pages/home/homePageController.ts
bower.json
package.json

App fix to not show guided tour at lower resolutions.

Bump common version to 0.0.35

---

dist/less/saas-list.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/saas-list/saas-list.controller.ts
src/styles/saas-list.less

Show at most 4 Saas Offerings at lg resolutions

---

test/services-view.spec.ts
test/utils/ComponentTest.ts

Safari does not support event.initKeyEvent

Fix for unit tests on Mac

---

dist/less/saas-list.less
dist/less/services-view.less
dist/less/variables.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/services-view/services-view.controller.ts
src/styles/saas-list.less
src/styles/services-view.less
src/styles/variables.less

Fixes #299 
Adds a more accurate calculation for size of services view.
Resulting console:
@jennyhaines @serenamarie125 @beanh66 @cshinn

Minor Spacing & Sizing Tweaks

---

dist/less/services-view.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/services-view/services-view.controller.ts
src/components/services-view/services-view.html
src/styles/services-view.less

On Firefox, we try to calculate the height of the items before they are
rendered, causing layout problems. This PR also adds some basic
animation so that expanding a subcategory is not quite as janky.
@sg00dwin will look at improving the animations as part of #287
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1462103

Bug 1462103 - Fix timing issue calculating service items height

---

dist/origin-web-catalogs.js
src/components/select-project/select-project.controller.ts

Filter for deleted projects. Closes #268

Select Project Filter Update

---

dist/less/landing-page.less
dist/less/services-view.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/order-service/order-service.controller.ts
src/services/catalog.service.ts
src/styles/landing-page.less
src/styles/services-view.less

Part of fix for
https://github.com/openshift/origin-web-console/issues/1673

Changing default icon to fa-clone

---

dist/origin-web-catalogs.js
src/components/order-service/order-service.controller.ts

Set default bindType to none when ordering services

---

dist/less/overlay-panel.less
dist/origin-web-catalogs.css
src/styles/overlay-panel.less

Fixes bug where modal buttons weren't visible on iPhone SE

---

app/config.js

Updated this to work on #32 but I don't see that login loop happening anymore. This fix is still relevant though.

Comment out additional-servers block, leave as an example

---

bower.json
package.json

Update origin-web-common to 0.0.41

Bump version to 0.0.29

---

dist/origin-web-catalogs.js
src/services/builder-app.service.ts

Fixes https://github.com/openshift/origin-web-console/issues/1842
cc @johnkim76

Avoid error when no exposed ports in builder image

---

dist/origin-web-catalogs.js
src/components/services-view/services-view.controller.ts

Switch to mobile subcategory view when filter set from search input

---

dist/origin-web-catalogs.js
src/components/order-service/order-service.controller.ts

See also
https://github.com/openshift/origin-web-console/issues/255
https://github.com/openshift/origin-web-console/pull/1813

Use `apps` API group for deployments

---

dist/origin-web-catalogs.js
src/constants.ts

Update Interactive Learning Portal URL

---

bower.json
package.json

Update origin-web-common to 0.0.43 and bump origin-web-catalog to version 0.0.33

Version 0.0.33

---

bower.json
dist/less/projects-summary.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
package.json
src/components/projects-summary/projects-summary.controller.ts
src/components/projects-summary/projects-summary.html
src/styles/projects-summary.less
test/projects-summary.spec.ts

Bumped origin-web-common to version 0.0.44
Bumped patternfly to version 3.26.1
Bumped angular-patternfly to version 4.3.0

Use common modal popup utility

---

bower.json
dist/origin-web-catalogs.js
package.json
src/components/landing-page/landing-page.controller.ts
src/services/catalog.service.ts

Bumps origin-web-common to 0.0.46
Requires https://github.com/openshift/origin-web-common/pull/145
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1471033
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1435174

Bug 1471033 - Only request template metadata

---

dist/origin-web-catalogs.js
src/services/builder-app.service.ts

See https://github.com/openshift/origin-web-console/issues/1944

Fix bug where service and route were not created from builder image

---

bower.json
package.json

Cut a release to pick up the fix for https://github.com/openshift/origin-web-console/issues/1944

Bump version to 0.0.38

---

dist/origin-web-catalogs.js
src/components/order-service/order-service.controller.ts

First part of fix for https://github.com/openshift/origin/issues/15898 to show failures in the results page of the wizard.

Update failure checks during service provisioning

---

test/utils/ComponentTest.ts

Add a testing framework workaround for anchor clicks causing infinite test runs

---

bower.json
dist/origin-web-catalogs.js
package.json
src/components/services-view/services-view.controller.ts

Update to angular patternfly 4.5.4
Update or origin-web-common 0.0.49
Remove resolved TODO for ignoring empty filters.

Bump version to 0.0.40

---

dist/origin-web-catalogs.js
src/components/order-service/order-service.controller.ts

Use a secret for parameters when provisioning a service.
https://trello.com/c/IlDIJAz2

Support secret parameters for service instances

---

app/mockServices/mockData/services.ts
dist/less/services-view.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/catalog-filter/catalog-filter.component.ts
src/components/catalog-filter/catalog-filter.controller.ts
src/components/catalog-filter/catalog-filter.html
src/components/services-view/services-view.controller.ts
src/components/services-view/services-view.html
src/index.ts
src/services/catalog.service.ts
src/styles/services-view.less
test/services-view.spec.ts

https://trello.com/c/UWgrj6bL
Hi, here is what I have so far.  Please see list of open issues at bottom.
**Catalog Filter Panel:**
**Vendor Warning** (needs wordsmithing, warning icon replaced with info icon :-)
1. Is the Vendor alert icon and tooltip ok?
2. If none of the catalog items have vendor information, then we just show the Keyword input filter in the panel:
Is it worth having a filter dropdown with just one input field?  In this scenario, it seems like the input field should be visible on the same lines as the "15 Items".
3. I notice in the mock data we have for service-classes 'metadata' and 'externalMetadata', currently I'm putting vendor info. in 'metadata.providerDisplayName' just want to verify this is correct.
Thanks,
- Dave

Catalog Filter Panel

---

bower.json
package.json

angular-patternfly 4.5.4 -> 4.7.1
origin-web-common 0.0.49 -> 0.0.50

Bump version and dependency versions

---

app/mockServices/mockData/services.ts
dist/origin-web-catalogs.js
src/services/catalog.service.ts

We're looking for `providerDisplayName` in the wrong place, which is why the faceted filter for Vendor is not showing up.

Look for providerDisplayName in externalMetadata

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

Fixes https://github.com/openshift/origin-web-console/issues/1979

Fixes bug where subcategory items display is incorrect

---

bower.json
dist/origin-web-catalogs.js
package.json
src/components/create-from-builder/create-from-builder-results.html
src/components/create-from-builder/create-from-builder.controller.ts
src/components/order-service/order-service-bind.html
src/components/order-service/order-service-review.html
src/components/order-service/order-service.controller.ts
src/constants.ts

Also, do not show binding in progress until the service instance has been created.
Depends on origin-web-common release with https://github.com/openshift/origin-web-common/pull/167

Do not allow binding to applications if pod_presets is false.

---

dist/origin-web-catalogs.js
src/constants.ts

Update Middleware categories

---

dist/less/order-service.less
dist/origin-web-catalogs.css
src/styles/order-service.less

Supports https://github.com/openshift/origin-web-console/issues/2007

Fix bug where long project names cause scrollbar in add modal

---

dist/less/variables.less
dist/origin-web-catalogs.css
src/styles/variables.less

Changing color of sidebar to match what's in console

---

app/mockServices/mockBinding.service.ts
app/mockServices/mockData.service.ts
app/mockServices/mockData/services.ts
bower.json
dist/origin-web-catalogs.js
package.json
src/components/create-from-builder/create-from-builder.controller.ts
src/components/order-service/order-service.controller.ts

https://trello.com/c/y1lbFrbp
Instance -> ServiceInstance
Binding -> ServiceInstanceCredential
Bump origin-web-common to 0.0.56
Requires:
https://github.com/openshift/origin-web-common/pull/182

Adopt new service catalog resource names

---

app/mockServices/mockApplications.service.ts
app/mockServices/mockServices.module.ts
dist/origin-web-catalogs.js
src/components/order-service/order-service.controller.ts

Requires https://github.com/openshift/origin-web-common/pull/178

Use new ApplicationsService.getApplications utility

---

app/mockServices/mockConstants.service.ts
app/mockServices/mockData/services.ts
dist/origin-web-catalogs.js
src/constants.ts
src/services/catalog.service.ts
test/services-view.spec.ts

Publisher Synonyms

---

.travis.yml
bower.json
package-lock.json
package.json

Update origin-web-common to 0.0.57

Bump to version 0.0.46

---

dist/origin-web-catalogs.js
src/components/order-service/order-service-review.html
src/filters/secretUrl.ts
src/index.ts

Fixes a bug where the secret link was incorrect for a binding on the wizard results pane.
https://bugzilla.redhat.com/show_bug.cgi?id=1493439

Bug 1493439 - Pass correct secret-href to bind-result

---

bower.json
package-lock.json
package.json

Bump origin-web-catalog to 0.0.48 and update origin-web-common to 0.0.58.

Bump version to 0.0.48

---

bower.json
package.json

For once https://github.com/openshift/origin-web-catalog/pull/413 merges

Bumping version to v0.0.49

---

bower.json
dist/less/order-service.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
package.json
src/components/create-from-builder/create-from-builder-results.html
src/components/order-service/order-service-review.html
src/styles/order-service.less

Updating provisioning/create from builder status messaging for consistency

---

dist/origin-web-catalogs.js
src/constants.ts

Remove link to developers portal

---

dist/origin-web-catalogs.js
src/components/catalog-filter/catalog-filter.controller.ts

Catalog Search from any category/sub-category other than 'All' throws error

---

dist/origin-web-catalogs.js
src/services/builder-app.service.ts

Generate Generic and GitHub webhooks for builds

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

Fixing bug where services with long names were getting clipped

---

dist/less/services-view.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
package-lock.json
src/constants.ts
src/styles/services-view.less

Recommended subcategories for Middleware templates from @sspeiche 
@rhamilto I might need some help with styling tiles that have longer labels.
@serenamarie125 FYI

Update Middleware subcategories

---

app/mockServices/mockAPI.service.ts
app/mockServices/mockData.service.ts
app/mockServices/mockData/plans.ts
app/mockServices/mockData/services.ts
bower.json
dist/origin-web-catalogs.js
package-lock.json
package.json
src/components/create-from-builder/create-from-builder.controller.ts
src/components/landing-page/landing-page.controller.ts
src/components/landing-page/landing-page.html
src/components/order-service/order-service-bind.html
src/components/order-service/order-service-info.html
src/components/order-service/order-service-plans.html
src/components/order-service/order-service.component.ts
src/components/order-service/order-service.controller.ts
src/components/services-view/services-view.component.ts
src/services/catalog.service.ts
test/services-view.spec.ts

https://trello.com/c/y1lbFrbp
Requires https://github.com/openshift/origin-web-common/pull/199
Bumps origin-web-common 0.0.63 -> 0.0.64
@jeff-phillips-18 FYI

Adopt service catalog API changes

---

bower.json
package.json

Supports https://github.com/openshift/origin-web-console/issues/2232

Bumping origin-web-common version to v0.0.65

---

dist/origin-web-catalogs.js
src/components/projects-summary/projects-summary.controller.ts

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1500859

Bug 1500859 - Fix incorrect project summary count

---

dist/origin-web-catalogs.js
src/components/overlay-panel/overlay-panel.controller.ts

Close the overlay panel on ESC

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

Increase space between add methods to make options distinct

---

dist/less/order-service.less
dist/origin-web-catalogs.css
dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder-configure.html
src/components/create-from-builder/create-from-builder.controller.ts
src/components/order-service/order-service-configure.html
src/components/order-service/order-service.controller.ts
src/components/select-project/select-project.component.ts
src/components/select-project/select-project.controller.ts
src/components/select-project/selectProject.html
src/styles/order-service.less

**Todo:**
Fixes #477
Fixes #494
**Latest Screenshots**
*Captions below screenshots*
---
---
---
---
---

Correct handling of select-project dropdown based on number of projects and can create privileges

---

dist/less/catalogParameters.less
dist/origin-web-catalogs.css
src/styles/catalogParameters.less

Fixes https://github.com/openshift/origin-web-console/issues/2321

Fix for mobile vertical alignment of readonly catalog parameters

---

dist/origin-web-catalogs.js
src/components/catalog-parameters/catalog-parameters.component.ts
src/components/catalog-parameters/catalog-parameters.controller.ts

This allows specified values to be shown while in hidden values mode.

Add opaque keys option to catalog parameters component

---

bower.json
package-lock.json
package.json

Bump patternfly versions to catchup with console.

Bump version to 0.0.58

---

dist/origin-web-catalogs.js
src/decorators/bootstrap/default.html
src/filters/escapeRegExp.ts
src/index.ts

Let the user confirm the entered password values when provisioning a service.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1504973

Bug 1504973 - Confirm password values

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

Add bottom margin to filter panel when under sub-category

---

bower.json
dist/origin-web-catalogs.js
package-lock.json
package.json
src/components/order-service/order-service.controller.ts
src/components/update-service/update-service.controller.ts

Bumps origin-web-common to 0.0.70
https://github.com/openshift/origin-web-common/releases/tag/v0.0.70
Requires https://github.com/openshift/origin-web-common/pull/235

Adopt renamed service external name properties

---

bower.json
package-lock.json
package.json

For service catalog API changes (#524 )

Bump version to 0.0.60

---

app/mockServices/mockAuthorization.service.ts

Mock AuthorizationService.getProjectRules()

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

Supports https://github.com/openshift/origin-web-console/issues/2454
Note:  @jennyhaines requested some tweaks that make this implementation different from [her mock](https://github.com/openshift/origin-web-console/issues/2454#issuecomment-342304860).
as seen in the console:
cc: @openshift/team-ux-review

Change subcategory styling

---

bower.json
package-lock.json
package.json

Bump version to 0.0.65

---

app/mockServices/mockData/services.ts
dist/origin-web-catalogs.js
src/constants.ts

Based on: https://bugzilla.redhat.com/show_bug.cgi?id=1512473
@spadgett PTAL

Bug 1512461 - Should capitalize the first letter for MySQL on the home page

---

bower.json
package-lock.json
package.json

Bump version to 0.0.66

---

dist/origin-web-catalogs.js
src/components/services-view/services-view.controller.ts

Fixes endless spinner issue for Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1501785

Fixed endless spinner when no catalog items available

---

dist/less/projects-summary.less
dist/origin-web-catalogs.css
src/styles/projects-summary.less

Fix bug where project description doesn't wrap in IE11

---

dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder-configure.html
src/components/create-from-builder/create-from-builder.controller.ts
src/services/builder-app.service.ts

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1519096
3.7 backport of #576
/kind bug

[3.7] Bug 1519096 - Use sample repository git ref and context dir

---

app/mockServices/mockData/openshift-images.ts
dist/origin-web-catalogs.js
src/components/create-from-builder/create-from-builder-configure.html
src/components/create-from-builder/create-from-builder.controller.ts

Correctly handle image stream tag aliases to the same image stream when
the name is included (from "nodejs:6" instead of "6").
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1518497
Backport of #574
/kind bug

[3.7] Bug 1518497 - Handle image stream tag aliases that include name

---

bower.json
package-lock.json
package.json

Bump version to 3.7.1

---

dist/less/landing-page.less
dist/origin-web-catalogs.css
src/styles/landing-page.less

Make search focus state more prominent

---

app/app.ts
app/mockServices/mockBinding.service.ts
src/components/update-service/update-service.controller.ts

Fixes for build warnings, failure with node 6.9.0

---

dist/origin-web-catalogs.js
src/components/update-service/update-service.controller.ts

...for just a couple api calls not using preferred version.

Update update-service component to use getPreferredVersion

---

dist/origin-web-catalogs.js
src/components/order-service/order-service.controller.ts

~~I believe this is the last of the `api-groups` updates, if my `grep` skills have not failed me.~~
one more  to go 😄

Update order-service component to use getPreferredVersion

---

dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/services-view.less

Supports https://github.com/openshift/origin-web-console/issues/2592
cc: @jennyhaines

Refactor services-view styles for within a project

---

bower.json
package-lock.json
package.json

Waiting on https://github.com/openshift/origin-web-catalog/pull/602 and https://github.com/openshift/origin-web-catalog/pull/603

Bump version to v3.9.0-alpha.1

---

bower.json
package-lock.json
package.json

/assign @jwforres 
/cc @jwforres @rhamilto

Bump version to 3.9.0-alpha.3

---

dist/less/animations.less
dist/less/services-view.less
dist/origin-web-catalogs.css
src/styles/animations.less
src/styles/services-view.less

@sg00dwin, since you added the animation, I wanted to double check with you regarding the removal.  You good with this?
Before:
http://recordit.co/ArZRSusG8i
After:
http://recordit.co/0hRnMxbb5Q
Related:  https://bugzilla.redhat.com/show_bug.cgi?id=1531477

Remove service-item animations to resolve filter bug

---

dist/less/overlay-panel.less
dist/origin-web-catalogs.css
src/styles/overlay-panel.less

And remove some orphaned rules
Supports https://github.com/openshift/origin-web-console/issues/2661
Before:
After:

Add option for overlay-panel to display as modal

---

bower.json
dist/origin-web-catalogs.js
package-lock.json
package.json
src/components/create-from-builder/create-from-builder.controller.ts

Closes https://github.com/openshift/origin/issues/17552

Sort image stream tags by semver when possible

---

bower.json
package-lock.json
package.json

/cc @benjaminapetersen @dtaylor113

Bump version to 3.9.0-alpha.13

---

app/mockServices/mockServices.module.ts
app/mockServices/mockVersions.service.ts
bower.json
dist/origin-web-catalogs.js
package-lock.json
package.json
src/components/create-from-builder/create-from-builder.controller.ts
test/services-view.spec.ts

Sort image stream tags by semantic version when possible

---

bower.json
package-lock.json
package.json

Bump version to 3.9.0-alpha.14

---

dist/less/landing-page.less
dist/origin-web-catalogs.css
src/styles/landing-page.less

Before:
http://g.recordit.co/TsJrOYg2b8.gif
After:
http://g.recordit.co/jq2toEwUpk.gif

Resolve bug where repaint bug occurs in Chrome on retina displays

---

bower.json
package-lock.json
package.json

Bump version to 3.9.0-rc.0

---

bower.json
package-lock.json
package.json

/assign @rhamilto
@jwforres FYI

Bump version to 3.9.0

---

bower.json
package-lock.json
package.json

Bump version to 3.10.0-alpha.0

---

dist/origin-web-catalogs.js
src/components/services-view/services-view.controller.ts

Catalog version of https://github.com/openshift/origin-web-console/pull/2870

Bug 1549450 - Better to use the same name for Clear filters, Clear Filter, Clear All Filters

---

bower.json
package-lock.json
package.json

Bump common version to 3.10.0-alpha.0

---

package-lock.json

Bump npm dependencies

---

app/mockServices/mockKeywords.service.ts
dist/origin-web-catalogs.js
src/components/catalog-search/catalog-search.controller.ts
src/components/services-view/services-view.controller.ts
src/constants.ts

https://trello.com/c/2fFSJMX1
https://bugzilla.redhat.com/show_bug.cgi?id=1449038
Requires https://github.com/openshift/origin-web-common/pull/317

Bug 1449038 - Improve catalog search

---

bower.json
package-lock.json
package.json

Bump version to 3.10.0-alpha.1

---

bower.json
package-lock.json
package.json

Bump version to 3.10.0
